language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: sh scripts/deploy.sh

after_success:
  branches:
    only:
      - develop
  - curl --user streetvoice:ru,g/upm,4 http://54.64.109.21:5000/deploy/streetvoice
