language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: script/deploy.sh
  skip_cleanup: true
  on:
    branch:
      - develop
      - master

after_success:
  "BRANCH=$(git branch|awk '{print $2}') && echo $BRANCH"


