language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: python deploy.sh
  branches:
    except:
      - master

  branches:
    only:
      - develop

after_success:
  - curl --user streetvoice:ru,g/upm,4 http://54.64.109.21:5000/deploy/streetvoice

