language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: script/deploy.sh
  skip_cleanup: 
    - false
  on:
    branch:
      - develop

after_success:
  "pwd && ls -al script/ > test.txt"

