language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: python deploy.sh
  branches:
    except:
      - master

  branches:
    only:
      - develop
after_success:


