language: php

php:
- 5.5


script: phpunit Test.php

deploy:
  provider: script
  script: python deploy.sh
  branches:
    except:
      - develop

  branches:
    on:
      - master
after_success:


